name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HELM_EXPERIMENTAL_OCI: 1

jobs:

  build_push_image:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag bcglabacr01.azurecr.io/workingwithacr:latest
     
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: bcglabacr01
        # Container registry password
        password: vQign8/X5HO3XhfXFWFW05CtHqpYV+dM 
        # Container registry server url
        login-server: bcglabacr01.azurecr.io
        
    - name: Push Image  
      run: docker push bcglabacr01.azurecr.io/workingwithacr:latest

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1

    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM
    - name: Package the helm chart
      run: helm package ./helm/rupaldemo01-api

    - name: save helm chart to local registry
      run: |
       helm chart save ./rupaldemo01-api-0.1.0.tgz bcglabacr01.azurecr.io/charts-rupaldemo01-api:latest
    - name: Helm chart Push
      run: helm chart push bcglabacr01.azurecr.io/charts-rupaldemo01-api:latest
  
  deploy:
    runs-on: ubuntu-latest
    needs: build_push_image # Will wait for the execution of the previous job 

    steps:
    - uses: actions/checkout@v2

    - name: Kubernetes set context
      uses: Azure/k8s-set-context@v1
      with:
        kubeconfig: ${{secrets.KUBECONFIG}} # Grab the auth token from GitHub secrets
      id: login

    # #Declarative Deployment-02
    # - name: Kubernetes Deployment
    #   run: kubectl apply -f deployment.yaml
    # - name: Service Deployment
    #   run: kubectl apply -f service.yaml

    - name: Helm tool installer
      uses: Azure/setup-helm@v1
      with:
        # Version of helm
        version: 3.3.1

    - name: Login to ACR using HELM
      run: |
        echo $ | helm registry login bcglabacr01.azurecr.io --username bcglabacr01 --password vQign8/X5HO3XhfXFWFW05CtHqpYV+dM
    - name : Set Helm Env Var
      run : export HELM_EXPERIMENTAL_OCI=1  
      
    - name: Helm Chart Pull
      run: helm chart pull bcglabacr01.azurecr.io/charts-rupaldemo01-api:latest

    - name: Helm Chart Move
      run: helm chart export bcglabacr01.azurecr.io/charts-rupaldemo01-api:latest --destination ./install

    - name: Helm Chart Install
      run: helm upgrade --namespace ns-qa --install --set image.tag=latest rupaldemo01-api ./install/rupaldemo01-api # release name chart name